yarnPath: ".yarn/releases/yarn-berry.js"
pnpMode: "loose"
pnpFallbackMode: "all"
packageExtensions:
  "@firebase/firestore@*":
    dependencies:
      "protobufjs": "*"
  # TODO: open a PR
  "next@*":
    dependencies:
      "schema-utils": "^1.0.0"
  # TODO: do we need to use this library still?
  "react-instantsearch@*":
    dependencies:
      "react": ">= 16.3.0 < 17"
  "tsutils@*":
    dependencies:
      "typescript": "*"
  "@typescript-eslint/typescript-estree@*":
    optionalDependencies:
      "typescript": "*"
  "eslint-plugin-prettier@*":
    dependencies:
      "prettier": "*"