# packageExtensions:
#   "@firebase/app-types@*":
#     dependencies:
#       "@firebase/logger": "^0.2.6"
#   "@firebase/firestore@*":
#     dependencies:
#       protobufjs: "*"
#   "@typescript-eslint/typescript-estree@*":
#     optionalDependencies:
#       typescript: "*"
#   eslint-plugin-prettier@*:
#     dependencies:
#       prettier: "*"
#   next@*:
#     dependencies:
#       schema-utils: ^1.0.0
#   react-instantsearch@*:
#     dependencies:
#       react: ">= 16.3.0 < 17"
#   tsutils@*:
#     dependencies:
#       typescript: "*"

pnpFallbackMode: all

pnpMode: loose

yarnPath: .yarn/releases/yarn-2.4.0.cjs
