service: syllabank

provider:
  name: google
  runtime: nodejs10
  project: syllabank-4e5b9
  region: us-central1

plugins:
  - serverless-google-cloudfunctions
  - serverless-dotenv-plugin

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  registerSyllabi:
    handler: registerSyllabi
    events:
      - event:
          eventType: google.storage.object.finalize
          resource: projects/_/buckets/${self:provider.project}.appspot.com
  syncDepartment:
    handler: syncDepartment
    events:
      - event:
          eventType: google.pubsub.topic.publish
          resource: projects/${self:provider.project}/topics/department-refreshed
  updateIndex:
    handler: updateIndex
    events:
      - event:
          eventType: providers/cloud.firestore/eventTypes/document.write
          resource: projects/${self:provider.project}/databases/(default)/documents/courses/{course}